### ISSUE TITLE
Anti-Matter Relays?

### ISSUE THREAD

**Issue by tjp73** [royal-reject-studios/Auxilium-Equivalence#1]
I am running the 1.15.2 version of Minecraft with the newest release of Projecte and Forge; when I downloaded the new release of Auxilium and started up the game, there were no Anti-Matter Relay Mk4-7. The Energy collectors are there but not the Relays. Is there something that I missed?
![2020-04-13_02 12 29](https://user-images.githubusercontent.com/63581384/79104841-a3e5c980-7d2c-11ea-83fc-da809bbd260f.png)
![2020-04-13_02 16 19](https://user-images.githubusercontent.com/63581384/79104929-d2fc3b00-7d2c-11ea-95dd-bfc4f905d83b.png)

**Comment by Colton-Slayden** [comment]
No the relays are on the way I wanted to get out a version to see if there is still a drive for this but the relays are coming!
